ciphertext.aes:
	python zad1.py enc_aes > $@

decrypted.aes:
	python zad1.py dec_aes > $@

ciphertext.des3:
	python zad1.py enc_des3 > $@

decrypted.des3:
	python zad1.py dec_des3 > $@

clean:
	rm *.{aes,des3}

.PHONY: clean
